@startuml
participant User
participant App
participant "Product Center" as PC
participant "Order Center" as OC

User -> App : Browse product list, find desired product
User -> App : Click to enter product details page
App -> PC : Query product details
PC --> App : Product details
User -> App : Click to checkout (Click to buy immediately)
App <--> User : Redirect to product preview page (Order form)
App -> OC: Pre-order interface generates product order details
User -> App : Select shipping address, select discount
User -> App : Go to payment
App <--> User: Redirect the payment page
App -> OC : Submit order (a series of verifications)
User -> App : Select payment method, pay

@enduml